name: PHP Tests


on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        coverage: 'pcov'
        extensions: mbstring, xml, zip

 

  #  - name: Install Dependencies
   #   run: |
    #    sudo apt-get update
     #   sudo apt-get install -y php-curl php-xml
      #  curl -sS https://getcomposer.org/installer -o composer-setup.php
       # sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer

    - name: Setup WordPress
      run: |
        composer install --no-dev --prefer-dist
        wp core install --url="http://localhost:8888" \
        --title="My WordPress Site" \
        --admin_user=admin \
        --admin_password=password \
        --admin_email=admin@example.com \
        --skip-email

    - name: Run Tests
      run: |
        vendor/bin/phpunit tests/
